DROP SCHEMA IF EXISTS ubd_20182 CASCADE;

CREATE SCHEMA ubd_20182 AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ubd_20182 TO postgres;

SET search_path TO ubd_20182;

BEGIN WORK;

SET TRANSACTION READ WRITE;

SET datestyle = DMY;


CREATE TABLE PERSON(
	id SMALLINT,
	name VARCHAR(255) NOT NULL,
	birth DATE NOT NULL,
	death DATE,
	gender VARCHAR(255) NOT NULL,
	nationality VARCHAR(255) NOT NULL,
	CONSTRAINT PK_PERSON PRIMARY KEY(id));

CREATE TABLE DIRECTOR(
	id SMALLINT,	
	debut_year SMALLINT NOT NULL,
	num_awards SMALLINT NOT NULL,
CONSTRAINT PK_DIRECTOR PRIMARY KEY(id), 
CONSTRAINT FK_PERSON FOREIGN KEY (id) REFERENCES PERSON(id));


CREATE TABLE ACTOR(
	id SMALLINT,
	debut_year SMALLINT,
	num_awards SMALLINT NOT NULL,
CONSTRAINT PK_ACTOR PRIMARY KEY(id));

CREATE TABLE MOVIE(
	id SMALLINT,
	title VARCHAR(255) NOT NULL,
	genre VARCHAR(255) NOT NULL,
	year SMALLINT NOT NULL,
	country VARCHAR(255) NOT NULL,
	duration SMALLINT NOT NULL,
	budget REAL NOT NULL,
	incomes REAL NOT NULL,
	id_prev_movie SMALLINT,
CONSTRAINT PK_MOVIE PRIMARY KEY(id),
CONSTRAINT FK_SAGA FOREIGN KEY (id_prev_movie) REFERENCES MOVIE(id),
CONSTRAINT POSITIVE_BUDGET CHECK (budget >= 0),
CONSTRAINT POSITIVE_INCOMES CHECK (incomes >= 0));


COMMIT;
